import { h, icon } from '../dom';
import type { Ctx } from '../main';
import { state, saveSubject } from '../state';
import { SYNTH_CASES } from '../../sim/ppgSynth';
import { unlockAudio } from '../audio';

export function renderSetup(main: HTMLElement, ctx: Ctx): void {
  const height = numberField('height', 'Height', 'cm', 100, 220, state.subject.heightCm,
    'Used to calculate the stiffness index, which divides your height by how long the reflected pulse wave takes to return.');
  const age = numberField('age', 'Age', 'years', 10, 110, state.subject.ageYears,
    'Shown next to the stiffness indicator for context, because arteries naturally stiffen with age. Not used in any calculation.');
  const error = h('p', { class: 'form-error', role: 'alert' });

  const start = () => {
    const hv = height.input.value.trim(), av = age.input.value.trim();
    const hn = Number(hv), an = Number(av);
    if (hv && (!Number.isFinite(hn) || hn < 100 || hn > 220)) { error.textContent = 'Enter a height between 100 and 220 cm, or leave it empty.'; height.input.focus(); return; }
    if (av && (!Number.isFinite(an) || an < 10 || an > 110)) { error.textContent = 'Enter an age between 10 and 110, or leave it empty.'; age.input.focus(); return; }
    state.subject = { heightCm: hv ? hn : undefined, ageYears: av ? an : undefined };
    saveSubject();
    unlockAudio();
    state.demoCaseId = null;
    ctx.go('capture');
  };

  main.append(
    h('section', { class: 'page' },
      h('div', { class: 'wrap narrow' },
        h('p', { class: 'kicker' }, 'New recording'),
        h('h1', { class: 'page-title' }, 'Before you record'),
        h('form', { class: 'setup-form', novalidate: true, onsubmit: (e: Event) => { e.preventDefault(); start(); } },
          h('fieldset', { class: 'panel form-panel' },
            h('legend', {}, 'About you'),
            h('p', { class: 'hint' }, 'Both are optional and stay on this phone.'),
            height.el, age.el,
          ),
          h('div', { class: 'panel form-panel' },
            h('h2', { class: 'panel-title' }, 'Get into position'),
            h('ol', { class: 'prep' },
              prep('Sit down and rest your hand and phone on a table.', 'Most failed recordings come from small hand movements.'),
              prep('Turn your sound on.', 'The phone clicks with each heartbeat, so you know it is working without looking.'),
              prep('Rest your fingertip lightly over the rear camera and flash.', 'Cover both completely. Pressing hard squeezes blood out of the fingertip and weakens the signal.'),
            ),
          ),
          error,
          h('div', { class: 'actions' },
            h('button', { class: 'btn', type: 'submit' }, icon('camera'), 'Start camera'),
            h('button', { class: 'btn quiet', type: 'button', onclick: () => ctx.go('home') }, 'Back'),
          ),
          h('p', { class: 'fine' }, 'Your browser will ask for camera access. The video is never saved or uploaded: VasoScan reads only the average brightness of each frame, on this phone.'),
        ),
      ),
    ),
  );
}

function numberField(id: string, label: string, unit: string, min: number, max: number, value: number | undefined, hint: string) {
  const input = h('input', { id, name: id, type: 'number', inputmode: 'numeric', min, max, value: value ?? '', 'aria-describedby': `${id}-hint`, autocomplete: 'off' });
  const el = h('div', { class: 'field' },
    h('label', { for: id }, label),
    h('div', { class: 'input-unit' }, input, h('span', { class: 'unit' }, unit)),
    h('p', { class: 'hint', id: `${id}-hint` }, hint),
  );
  return { el, input };
}

function prep(title: string, detail: string): HTMLLIElement {
  return h('li', {}, h('strong', {}, title), h('span', {}, detail));
}

export function renderDemoPicker(main: HTMLElement, ctx: Ctx): void {
  const run = (id: string) => {
    state.demoCaseId = id;
    state.captureSimulated = false;
    const c = SYNTH_CASES.find((x) => x.id === id)!;
    state.subject = { heightCm: c.heightCm, ageYears: c.ageYears };
    ctx.go('processing');
  };
  main.append(
    h('section', { class: 'page' },
      h('div', { class: 'wrap narrow' },
        h('p', { class: 'kicker' }, 'Demo recordings'),
        h('h1', { class: 'page-title' }, 'Choose a simulated recording'),
        h('div', { class: 'provenance simulated' }, icon('flask'),
          h('div', {}, h('strong', {}, 'These recordings are simulated'), 'They are generated by a pulse-wave model to show how VasoScan works without a camera. They are not measurements of real people. They run through exactly the same analysis as a live recording.'),
        ),
        h('ul', { class: 'case-list' },
          ...SYNTH_CASES.map((c) => h('li', {},
            h('button', { class: 'case', onclick: () => run(c.id) },
              h('span', { class: 'case-name' }, c.label),
              h('span', { class: 'case-summary' }, c.summary),
              h('span', { class: 'case-meta' }, c.artifact ? 'Shows a recording that fails the quality checks' : `Simulated profile: ${c.heartRate} beats/min, age ${c.ageYears}, height ${c.heightCm} cm`),
            ),
          )),
        ),
        h('button', { class: 'btn quiet', onclick: () => ctx.go('home') }, 'Back'),
      ),
    ),
  );
}
